### PR TITLE
Master

### PR DESCRIPTION
**Pull request by henicorhina**
added chapter 1

### CODE REVIEW

**Comment by brantfaircloth** [comment]
This still appears to remove the chapter-1 file at the top level...  (I can fix if necc., but I bet you can get it).

**Comment by brantfaircloth** [comment]
Oscar - i closed this one for the same reason as the last ones - it's still deleting the chapter file at the top level.

**Comment by henicorhina** [comment]
I'll just talk to you about this after class tomorrow. I apparently have no idea what you're talking about...

**Comment by brantfaircloth** [comment]
On 9 Mar 2016, at 20:58, Oscar Johnson wrote:

> I'll just talk to you about this after class tomorrow. I apparently 
> have no idea what you're talking about...

right on - i just fixed it for you.  can explain what deal was in class 
tomorrow.

-b

**Pull request closed without merging**
